services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - scheduler-app_network

  pgadmin:
    container_name: ${PGADMIN_CONTAINER_NAME}
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT_INTERNAL}
    ports:
      - "${PGADMIN_LISTEN_PORT_EXTERNAL}:${PGADMIN_LISTEN_PORT_INTERNAL}"
    depends_on:
      - postgres
    networks:
      - scheduler-app_network

  scheduler:
    container_name: ${SCHEDULER_CONTAINER_NAME}
    build: .
    volumes:
      - ./logs:/app/logs
    networks:
      - monitor_catalogo_net_catalogo_vtex
      - scheduler-app_network
    ports:
      - "5500:5500"
    command: /bin/sh -c "sleep 30 && uvicorn main:app --port 5500 --host 0.0.0.0"
    # environment:
    #   - API_TOKEN=${API_TOKEN}
    env_file:
      - .env
    depends_on:
      - postgres
        # condition: service_healthy

networks:
  scheduler-app_network:
    driver: bridge
  monitor_catalogo_net_catalogo_vtex:
    external: true
